### ISSUE TITLE
ErrorException

### ISSUE THREAD

**Issue by SuperlativeEntity** [Regulus343/ActivityLog#10]
exception 'ErrorException' with message 'Undefined index: HTTP_USER_AGENT' 
in vendor\regulus\activity-log\src\models\Activity.php:81

Can you please do a check to make sure the user agent is set?

http://stackoverflow.com/questions/14130830/php-undefined-index-http-user-agent 

Thanks

**Comment by kerwitz** [comment]
Actually there is a check for the index since 3d6b16c6c2253987d781d6cc9cf93829232a0415 and [v0.3.1](https://github.com/Regulus343/ActivityLog/releases/tag/v0.3.1). 
Did you install using composer? Which version are you on?
You may want to update your package.

**Comment by SuperlativeEntity** [comment]
Thanks for the reply. You're correct, my version is out of date. I will update and let you know if I run into any further issues.

**Comment by kerwitz** [comment]
:+1: good luck!
