### ISSUE TITLE
composer version not matching repo

### ISSUE THREAD

**Issue by jeroenbourgois** [Regulus343/ActivityLog#12]
Hi!

We are upgrading our Laravel version from `5.0.*` to `5.1.*`, and in the github repo the latest version of ActivityLog requires 5.1; but the last regular version (so not `dev-master`) still requires 5.0.*.

Could you create a new `0.5.3` tag that includes this update? We are now using the `dev-master` version but that does not seem ideal :)

Thanks!

**Comment by Regulus343** [comment]
Done. Thank you for the reminder!
