### ISSUE TITLE
best practice to use this package

### ISSUE THREAD

**Issue by moeinrahimi** [Regulus343/ActivityLog#23]
hi
i really like your package it is very useful, i'd like to use it for my elequent events, but i have one question what is the best way to this ? should i do this in every single of my models or there is a better approach to this ?

**Comment by Regulus343** [comment]
There may in fact be a better approach (and I'm open to suggestions for the best method of achieving this so that I can update the docs to reflect them), but that's what I've been doing.

**Comment by moeinrahimi** [comment]
I had found a repository for my question, it uses Trait and bootTraitName to run the trait in models automatically for saving user activity but it uses laravel 5 and there has been changes since then.
https://github.com/laracasts/Build-An-Activity-Feed-in-Laravel
