### ISSUE TITLE
preg_replace(): Parameter mismatch, pattern is a string while replacement is an array

### ISSUE THREAD

**Issue by moeinrahimi** [Regulus343/ActivityLog#24]
this is the example in readme i tried to run and test but it failed with issue title error.

  Activity::log([
        'contentType' => 'Record',
        'description' => [
            'created_items', [ // "activity-log::descriptions.created_items" is ":user created :number :items."
                'number' => 2,
                'items'  => 'SPL|labels.record', // "labels.record" in this example has a string of "Record|Records"
            ],
        ],
        'details' => [
            'record',
            'This is Some Kind of Record',
        ],
        'data' => [
            'category' => 'Content',
        ],
    ]);

**Comment by Regulus343** [comment]
Hmm, I just tested the same code and am not getting an error. Have you run `php artisan vendor:publish` to publish the config file?

**Comment by moeinrahimi** [comment]
yes of course , should i modify or add something in the log.php config ?

**Comment by Regulus343** [comment]
Sorry, I'm way late on the reply, but I would recommend trying it with the latest log.php and see if the issue persists.
