### ISSUE TITLE
Adding unique model identifier to activity log table

### ISSUE THREAD

**Issue by BlazeNikhilesh** [Regulus343/ActivityLog#25]
There could be cases where I just want to retrieve activity log for a particular model Id. 

It would be good to have that column in the table. Using which I can get activity logs for that particular id or array of ids.

**Comment by Regulus343** [comment]
You should be able to do this with the "content_type" and "content_id" columns. Please let me know if I have misinterpreted the issue. I would like to convert this to a polymorphic relationship for version 0.7.0.
