### ISSUE TITLE
Use ActivityLog with Mongo DB 

### ISSUE THREAD

**Issue by nicohell** [Regulus343/ActivityLog#32]
Hi

To use ActivityLog with Mongo DB, we need to call Jessengers instead of standart  Eloquent in Model

I don't really know the way to do, so I create a Fork of your repo and make the modification in a [branch](https://github.com/ICM-Services/ActivityLog/commit/6b642210ba7d945e8415ff1a66d878f1bfbafda6).

Regards
Nicolas

**Comment by Regulus343** [comment]
Referenced branch appears no longer to exist. Closing issue.
