### ISSUE TITLE
Get Logged In User IP address not public IP ?

### ISSUE THREAD

**Issue by mansouralex** [Regulus343/ActivityLog#7]
How to get Logged In User Private IP Address instead of the public IP Address ? Especially if we are talking about Intranet Applications.

Thank you.

**Comment by kerwitz** [comment]
There will only be one IP available to the package, PHP and the server each from the client and the host. Theres no way to access any other IP than the public one, thats the point of NAT after all. ;)

**Comment by mansouralex** [comment]
Thank you for your reply and clarifying this.

**Comment by kerwitz** [comment]
No problem :+1:, feel free to close this issue if you've got no more questions on this topic.

Also check [stackoverflow](http://stackoverflow.com) for general coding questions.
