### ISSUE TITLE
$this->user is null

### ISSUE THREAD

**Issue by giwrgos88** [Regulus343/ActivityLog#8]
I'm trying to access the name of the user but the $this->user inside the Activity model is always null. Why?

**Comment by dochoaj** [comment]
The user is related to:

```php
public function user()
{
   return $this->belongsTo(config('auth.model'), 'user_id');
}
```
So you should check if the auth model is well defined in app/config/auth.php at your laravel app.

**Comment by giwrgos88** [comment]
The model is defined to this path 'model' => 'APPPATH\Models\User', 'table' => 'users' and here is my model

namespace APPPATH\Models;

use Illuminate\Auth\Authenticatable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;
use Illuminate\Database\Eloquent\SoftDeletes;

class User extends Model implements AuthenticatableContract, CanResetPasswordContract {
}

which is inside App/Models/Users

**Comment by Regulus343** [comment]
A few things to check:

1) That you're using v0.3.1 for Laravel 4, and "dev-master" for Laravel 5 (a proper release for the Laravel 5 code base will probably happen within the next few days).

2) Try dumping config('auth.model') to verify that it is not null for some reason.

3) Try dumping Auth::user() to verify that it is not null either.

**Comment by giwrgos88** [comment]
2 and 3 i made it, what i made at the end is the following code, I'm sending the id of the users and then i'm returning back the name

	public function getUserName($id)
	{
		$user = config('auth.model');
		$user = new $user();
		$user = $user->where("id","=",$id)->select('user_display_name')->first();
		if (is_null($user))
		{
			return "User";
		}
		return $user["user_display_name"];
	}

**Comment by Regulus343** [comment]
I am wondering if there are problems with model relationships in general in your particular Laravel install then, because the relationship is a very simple belongsTo() which matches exactly the format in the Eloquent documentation.

**Comment by giwrgos88** [comment]
I don't know, but anyway i fix it temporarily the solution, with my function

**Comment by Regulus343** [comment]
Alright. I will close the issue then. Glad you found a workaround for your problem. I do suggest trying other Eloquent relationships though so that you can see if there is a problem with them in general.
